apiVersion: apps/v1
kind: Deployment
metadata:
  name: aigatekeeper
spec:
  selector:
    matchLabels:
      app: aigatekeeper
  replicas: 3 # tells deployment to run X pods matching the template
  template:
    metadata:
      labels:
        app: aigatekeeper
    spec:
      containers:
      - name: aigatekeeper
        image: nimababak/aigatekeeper
        ports:
        - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: aigatekeeper
spec:
  type: NodePort
  selector:
    app: aigatekeeper
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
    nodePort: 31000
---
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: aigatekeeper
#   annotations:
#     kubernetes.io/ingress.class: addon-http-application-routing
# spec:
#   rules:
#   # https://docs.microsoft.com/en-us/azure/aks/http-application-routing
#   - host: aigatekeeper.AKS_URL
#     http:
#       paths:
#       - path: /
#         pathType: Prefix
#         backend:
#           service:
#             name: aigatekeeper
#             port:
#               number: 80
