@startuml 
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Container.puml

LAYOUT_TOP_DOWN
'LAYOUT_AS_SKETCH
LAYOUT_WITH_LEGEND()

System_Boundary(c1, "AIGuardian.Orchistrator") {
  Container(app, "Service", "C#", "Watches for new files, when found sends them to the the detector and if an object of interest is detected sends the data to a repository.")
  Container(log, "Logger", "C#", "Writes relevent event information to a target log.")
  Container(detector, "Detector", "C#", "Communication routines for conversing with the detector.")

}

Rel(app, log, "Uses", "interface")
Rel(app, detector, "Uses", "interface")
@enduml