@startuml 
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/release/1-0/C4_Container.puml

System_Ext(filesys, "File System", "Source for Detections")
System_Ext(bus, "Message Bus")
System_Ext(notification, "Notifications")
System_Ext(workflow, "Workflow")
System_Ext(persist, "Storgage")

System_Boundary(bound, "AIGuardian") {
    System(discovery, "Item Discovery : AIGuard.Orchestrator")
    System(detector, "Item Detector : AIGuard.Broker")
    System(repo, "Repository : AIGuard.IRepository")
}

Rel(bus, workflow, "File system change")


Rel(workflow, notification, "Item of interest found")
Rel(discovery, detector, "Item of interest found")
Rel(detector, bus, "Item of interest found")
Rel(bus, repo, "Item of interest found")
Rel(repo, persist, "Item of interest found")

Rel(filesys, discovery, "File system change")

@enduml