@startuml test
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

title AIGatekeeper System Context Diagram

Person(recipient, "Notified person", "A person notified when an event of interest occurs")

System(guard, "AIGuardian")

System_Ext(filesys, "File System", "Source for Detections")
System_Ext(bus, "Message Bus")
System_Ext(notification, "Notifications")
System_Ext(workflow, "Workflow")

Rel(filesys, guard, "Files Added")
'Rel(guard, detector, "Files for detection engine")
'Rel_Back(guard, detector, "Detection results")
Rel(guard, bus, "Item of interest found")
Rel(bus, guard, "Item of interest found")
Rel(bus, workflow, "Item of interest found")
'Rel(bus, repo, "Item persisted")
Rel(workflow, notification, "Item of interest found")
Rel(notification, recipient, "Item of interest found")



@enduml
