@startuml test
!includeurl https://raw.githubusercontent.com/RicardoNiepel/C4-PlantUML/master/C4_Context.puml

title AIGatekeeper System Context Diagram

Person(recipient, "Notified person", "A person notified when an event of interest occurs")
System_Ext(sys, "File System", "Source for Detections")
System_Boundary(bound, "AIGuardian") {
    System(discovery, "Item Discovery : AIGuard.Orchestrator")
    System(detector, "Item Detector : AIGuard.Broker")
    System(repo, "Repository : AIGuard.IRepository")
}
System_Ext(bus, "Message Bus")
System_Ext(notification, "Notifications")
System_Ext(workflow, "Workflow")

Rel(sys, discovery, "Monitors")
Rel(discovery, detector, "Files for detection engine")
Rel_Back(discovery, detector, "Detection results")
Rel(discovery, bus, "Item of interest found")
Rel(bus, workflow, "Item of interest found")
Rel(bus, repo, "Item persisted")
Rel(workflow, notification, "Item of interest found")
Rel(notification, recipient, "Item of interest found")



@enduml
