name: Master_Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
    - name: Change directory
      run: cd src
    - name: List directories
      run: ls -la
    - name: Install dependencies
      run: |
        cd src 
        ls -ls 
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --configuration Release --no-restore
    - name: Run Infer#      
      uses: microsoft/infersharpaction@v1.2.1
      id: runinfersharp
      with:
        binary-path: '<path to the binary directory containing .dlls and .pdbs>'

    - name: Infer# analysis results
      run: echo "${{ steps.runinfersharp.outputs.results }}"        
