name: Master_Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: '6.0.x'
        include-prerelease: true
    - name: Change directory
      run: cd src
    - name: List directories
      run: ls -la
    - name: Install dependencies
      run: |
        cd src 
        ls -ls 
        dotnet restore
    - name: Build
      run: |
        cd src
        dotnet build --configuration Release --no-restore
#    - name: Test
#      run: |
#        cd src/AIGuard.UnitTests
#        dotnet test --no-restore --verbosity normal   
# Runs Parasoft dotTEST and generates the reports.

    - name: Run Parasoft dotTEST
      id: dottest
      uses: parasoft/run-dottest-action@1.1.0

    # Uploads analysis results in the SARIF format, so that they are displayed as GitHub code scanning alerts.
    - name: Upload results (SARIF)
      uses: github/codeql-action/upload-sarif@v1
      if: always()
      with:
        sarif_file: ${{ steps.dottest.outputs.report }}

    # Uploads an archive that includes all report files (.xml, .html, .sarif).
    - name: Archive reports
      uses: actions/upload-artifact@v2
      if: always()
      with:
        name: DottestReports
        path: ${{ steps.dottest.outputs.reportDir }}/*.*
