name: InferSharp_Test

on:
 workflow_dispatch:
 push:
   branches:
     - master

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
      - name: Infer# analysis results
        uses: microsoft/infersharpaction@v1.2.1
        id: runinfersharp
        with:
#         binary-path: '<path to the binary directory containing .dlls and .pdbs>'
#         binary-path: '/home/runner/work/AIGatekeeper/AIGatekeeper/src/AIGuard.Orchestrator/bin/Release/net5.0/AIGuard.Orchestrator.dll'
          binary-path: /home/runner/work/AIGatekeeper/AIGatekeeper/src/AIGuard.Orchestrator/bin/Release/net5.0/AIGuard.Orchestrator.dll

      - name: Infer# analysis results
        run: echo "${{ steps.runinfersharp.outputs.results }}"   
